### ISSUE TITLE
Erro ao tentar rodar os testes

### ISSUE THREAD

**Issue by felquis** [pagarme/pagarme-ruby#58]
Opa, eu rodei o comando `rake` e ele me deu o seguinte erro:

It shows:
```txt
/home/felquis/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- shoulda (LoadError)
	from /home/felquis/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/felquis/pagarme/pagarme-ruby/test/test_helper.rb:2:in `<top (required)>'
	from /home/felquis/pagarme/pagarme-ruby/test/pagarme/error_test.rb:1:in `require_relative'
	from /home/felquis/pagarme/pagarme-ruby/test/pagarme/error_test.rb:1:in `<top (required)>'
	from /home/felquis/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/felquis/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/felquis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /home/felquis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
	from /home/felquis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1)
/home/felquis/.rvm/gems/ruby-2.1.5/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/felquis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/felquis/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Não sei se é obvio para pessoas mais experientes com Ruby, mas aceito uma ajuda nisso. Vlw.

**Comment by drodrigo** [comment]
@felquis  você rodou `bundle install`? Se deu algum erro qual foi? =)

**Comment by felquis** [comment]
Era o `bundle install` mesmo, obrigado!

**Comment by felquis** [comment]
![](https://media.giphy.com/media/IL4iTvQH0MjS/giphy.gif)
